return {
	Rifleman = {
		branch = "Army",
		unlockBuilding = "Armory",
		unlockLevel = 1,
		combatPower = 10,
		suppression = 0,
		movement = 1,
	},

	TeamLeader = {
		branch = "Army",
		unlockBuilding = "Barracks",
		unlockLevel = 1,
		combatPower = 11,
		suppression = 0,
		movement = 1,
		commandBonus = 1,
	},

	AutomaticRifleman = {
		branch = "Army",
		unlockBuilding = "Armory",
		unlockLevel = 2,
		combatPower = 12,
		suppression = 2,
		movement = 0.85,
	},

	Grenadier = {
		branch = "Army",
		unlockBuilding = "Armory",
		unlockLevel = 2,
		combatPower = 11,
		suppression = 1,
		movement = 0.9,
		areaDamage = 1,
	},
}
